### ISSUE TITLE
Todo list for Homework 2

### ISSUE THREAD

**Issue by s6ribaum** [Trico94/physics760_Martin#2]
- [x] Exercise 2 (How does the numerical cost of the calculation of the energy (for a given spin configuration) scale with the system size Lambda?)

- [x] Exercise 3 (Assuming you’ve flipped one spin s, how does the numerical cost of the calculation of the change in energy Delta S scale with the system size Lambda?)

- [x] Exercise 4 (What is the significance of the critical coupling J_c ?)

- [x] Exercise 6 (Use your algorithm to estimate <epsilon>?)
For that we have to implement:
   - [x] analytical solution
   - [x] computed solution

- [x] Exercise 7 (Use your algorithm to estimate <|m|>?)
For that we have to implement:
   - [x] analytical solution
   - [x] computed solution

I think I can implement Exercise 6 and Exercise 7 tomorrow.

**Comment by s6ribaum** [comment]
I don`t know if you got the mail with the correction of the first hand in, but it was wanted that we make a PDF for the next solutions. I set up a basic PDF structure in my and the main branch. Therefore:

- [x] Write PDF

**Comment by s6ribaum** [comment]
Concerning the PDF I just found out, that the command

`ipython nbconvert --to html exercise2.ipynb`

can convert the jupyter notebook into a html file. This can then be opend with a browser and print with a "pdf" printer. Which turns the file into a pdf. Therefore there is no need for a latex document. However whoever chooses to write the PDF he can check the text in the Notebook.

**Comment by s6ribaum** [comment]
Everything is done, only bugfixes to do
